prom_targets:
  - name: prometheus_up_demo
    base_url: http://host.docker.internal:8085
    timeout_seconds: 10
    verify_tls: true
    runtime:
      default_interval_seconds: 45
      sleep_seconds: 1
      dry_run: false
    jobs:      
      - name: prometheus_build
        query: up
        interval_seconds: 30
        nodes:
          - types: 
              - PROMETHEUSJOB
            template_hashes:
              - b23b5cb54b411990
            update_policy: merge
            expiration_time_min: 10
            label_properties:
              name: job
              job: job

          - type: PROMETHEUSTARGET
            template_hashes:
              - 0141ecd65eec3ec9
            static_properties:
              kind: scrape_target
            label_properties:
              name: instance
              job: job
              instance: instance
              status: __value__
            property_transforms:
              - property: kind
                process:
                  - type: REGEX
                    pattern: "/(\\w+)_(\\w+)/"
                    output: "$1_is_kind"
                  - type: TO_UPPER

        relationships:
          - type: SCRAPES
            template_hash: 8c2c0b2cdbab83d6
            update_policy: merge
            source:
              type: PROMETHEUSJOB
              match_attributes:
                labels:
                  name: job
            target:
              type: PROMETHEUSTARGET
              match_attributes:
                labels:
                  name: instance
